### ISSUE TITLE
Presenters and automatic reload raises an exception

### ISSUE THREAD

**Issue by sophiedeziel** [kernow/shortcode#30] opened 2015-05-15 17:22 UTC
I am opening an issue to know if I should do something else in my project or if it is possible to improve the shortcode gem. 

I created my presenters in the app/presenters directory in my rails app to get automatic reload in development environment so I don't have to restart the server when I change something in a presenter. The presenters are registered in an initializer.

However, when I modify a presenter, on the next load of a page using shortcode, I get that exception:

```
A copy of ExamplePresenter has been removed from the module tree but is still active!
```

I was able to fix this temporarily by registering my presenters in my controller, but I don't like the idea. 

The other solution I think would be good is to change the register implementation to store string of the class name instead of the class itself. So the class can be reloaded and called over and over dynamically.

```
def register(presenter)
  validate presenter
  [*presenter.for].each { |k| presenters[k.to_sym] = presenter.to_s } 
end
```

Then each time the class is needed, we'll have to use  ``` "Classname".constantize ```. Maybe we should make a getter method... 

I'm not 100% sure this will fix the problem, so I will be working on it. If that's not the solution, I will tell you. If it is, I will create a PR. If you have a better idea, I'd like to try it.

**Comment by mtarnovan** [comment] 2015-09-18 07:34
I have the same issue, would it be possible to merge this? I understand @kernow had some objection for using this fix in production, but I'm not sure what the issues could be? 

@sophiedeziel I suggest using [`safe_constantize`](http://api.rubyonrails.org/classes/ActiveSupport/Inflector.html#method-i-safe_constantize) instead of `constantize`

**Comment by kernow** [comment] 2015-09-18 08:27
@mtarnovan I'll have a look at this later today, the main reason I haven't merged is because I've not had the time, there were a few tweaks I wanted to make before merging that I haven't got around to yet.

**Comment by mtarnovan** [comment] 2015-09-18 10:02
Ok, let me know if I can help.

**Comment by kernow** [comment] 2015-09-18 10:57
Ok so the issue is that contstantize is a rails method so it can't be used. Another way will need to be found to solve this issue.

**Comment by mtarnovan** [comment] 2015-09-18 12:13
How about `Module.const_get`or cherry-picking ActiveSupport's `constantize`?

**Comment by sophiedeziel** [comment] 2015-09-18 14:36
Oh, I did not know that about `constantize`. `Module.const_get` seems an excellent approach. It would make us use symbols instead of strings, which is also good.

**Comment by kernow** [comment] 2015-09-18 17:49
I think this will cause more problems for other users as const_get does not work for all situations e.g. `Foo::Bar`. Could you try registering your presenters as `::ExamplePresenter` rather than `ExamplePresenter` to see if that fixes the situation?

**Comment by sophiedeziel** [comment] 2015-09-18 18:23
I will experiment with every scenarios I can think of and write the proper tests for it. Thanks for the feedback :smile:

**Comment by kernow** [comment] 2015-09-18 18:26
@sophiedeziel I meant trying out `Shortcode.register_presenter(::CustomPresenter)` rather than changing anything within the gems code. See if this resolves your problem first.

**Comment by sophiedeziel** [comment] 2015-09-18 21:34
That would be awesome if it's solving it. I can't remember, I think I tried a couple of months ago and it didn't. But honestly, it's hard to remember.

**Comment by mtarnovan** [comment] 2015-09-19 06:15
What about:

```ruby
2.0.0-p353 :003 > module Foo; module Bar;class Baz; end;end;end
 => nil 
2.0.0-p353 :004 > 'Foo::Bar::Baz'.split('::').reduce(Module, :const_get)
 => Foo::Bar::Baz 
```

**Comment by kernow** [comment] 2015-09-19 07:55
I think this is a problem with the rails class reloading in development that's not related to Shortcode. If your presenters are in the /app directory they they are set to reload on each request. If this issue is only happening occasionally then it's likely that it's something outside of Shortcode causing the problem.

If it's only happening occasionally (and not on every request) then restarting the rails app isn't much of an issue. I'm going to close this issue for now.

**Closed by kernow** 2015-09-19 07:55 UTC

**Comment by sophiedeziel** [comment] 2015-09-21 14:36
@mtarnovan to reproduce it, change something in your presenter file. Each time the class changes, it is reloaded but the reference we keep remains the same. I'll have a look on other gems to see what strategy they use when they have to register classes and keep a reference to them.

Another solution would be to have the presenters in the `lib/` directory, but we'll have to restart our server each time we modify our presenters.

**Comment by mtarnovan** [comment] 2015-09-21 23:26
For some reason this issue happens for us from time to time even without changing a presenter file, and after it happens a server restart is required for it to go away. Obviously not a blocker, but rather annoying, so I'd like to find a fix other than moving the presenters out of `autoload_path`.
